---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: koku-metrics-operator-manager-config-rolebinding
  namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: koku-metrics-operator-manager-config-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: openshift-cost
