apiVersion: koku-metrics-cfg.openshift.io/v1alpha1
kind: KokuMetricsConfig
metadata:
  name: kokumetricscfg-sample
spec:
  authentication:
    type: token
  packaging:
    max_size_MB: 100
  prometheus_config: {}
  source:
    check_cycle: 1440
    create_source: false
  upload:
    upload_cycle: 360
    upload_toggle: true
