apiVersion: v1
kind: ConfigMap
metadata:
  namespace: koku-metrics-operator
  name: trusted-ca-bundle
  annotations:
    release.openshift.io/create-only: "true"
    service.beta.openshift.io/inject-cabundle: "true"
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
