apiVersion: v1
kind: Service
metadata:
  name: koku-metrics-webhook-service
  namespace: koku-metrics-operator
  annotations:
   service.beta.openshift.io/serving-cert-secret-name: koku-metrics-webhook-service
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: controller-manager
