# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/costmanagement-metrics-cfg.openshift.io_costmanagementmetricsconfigs.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# - patches/webhook_in_kokumetricsconfigs.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CA injection] To enable webhook, uncomment all the sections with [CA injection] prefix.
# patches here are for enabling the CA injection for each CRD
# - patches/cainjection_in_kokumetricsconfigs.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
