
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: costmanagements.cost-mgmt.openshift.io
spec:
  group: cost-mgmt.openshift.io
  names:
    kind: CostManagement
    listKind: CostManagementList
    plural: costmanagements
    singular: costmanagement
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CostManagement is the Schema for the costmanagements API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CostManagementSpec defines the desired state of CostManagement
          properties:
            api_url:
              description: APIURL is a field of CostManagement to represent the url
                of the API endpoint for service interaction.
              type: string
            authentication:
              description: Authentication is a field of CostManagement to represent
                the authentication object.
              properties:
                secret_name:
                  description: AuthenticationSecretName is a field of CostManagement
                    to represent the secret with the user and password used for uploads.
                  type: string
                type:
                  description: 'AuthType is a field of CostManagement to represent
                    the authentication type to be used basic or token. Valid values
                    are: - "basic" : Enables authetication using user and password
                    from authentication secret - "token" (default): Uses cluster token
                    for authentication'
                  enum:
                  - token
                  - basic
                  type: string
              type: object
            clusterID:
              description: ClusterID is a field of CostManagement to represent the
                cluster UUID.
              type: string
            file_directory:
              description: FileDirectory is a field of CostManagement to represent
                the location of stored files.
              type: string
            prometheus_config:
              description: PrometheusConfig is a field of CostManagement to represent
                the configuration of Prometheus connection.
              properties:
                service_address:
                  description: SvcAddress is a field of CostManagement to represent
                    the thanos-querier address.
                  type: string
                skip_tls_verification:
                  description: SkipTLSVerification is a field of CostManagement to
                    represent if the thanos-querier endpoint must be certificate validated.
                    The default is false.
                  type: boolean
              type: object
            source:
              description: Source is a field of CostManagement to represent the desired
                source on cloud.redhat.com.
              properties:
                check_cycle:
                  description: CheckCycle is a field of CostManagement to represent
                    the number of minutes between each source check schedule The default
                    is 1440 min (24 hours)
                  format: int64
                  minimum: 0
                  type: integer
                create_source:
                  description: CreateSource is a field of CostManagementSpec to represent
                    if the source should be created if not found.
                  type: boolean
                name:
                  description: SourceName is a field of CostManagementSpec to represent
                    the source name on cloud.redhat.com.
                  type: string
                sources_path:
                  description: SourcesAPIPath is a field of CostManagement to represent
                    the path of the Sources API service. The default is /api/ingress/v1.0/sources/
                  type: string
              type: object
            upload:
              description: Upload is a field of CostManagement to represent the upload
                object.
              properties:
                ingress_path:
                  description: IngressAPIPath is a field of CostManagement to represent
                    the path of the Ingress API service. The default is /api/ingress/v1/upload/
                  type: string
                upload_cycle:
                  description: UploadCycle is a field of CostManagement to represent
                    the number of minutes between each upload schedule The default
                    is 360 min (6 hours)
                  format: int64
                  minimum: 0
                  type: integer
                upload_toggle:
                  description: UploadToggle is a field of CostManagement to represent
                    if the operator should upload to cloud.redhat.com. The default
                    is true
                  type: boolean
                upload_wait:
                  description: UploadWait is a field of CostManagement to represent
                    the time to wait before sending an upload.
                  format: int64
                  minimum: 0
                  type: integer
              type: object
            validate_cert:
              description: ValidateCert is a field of CostManagement to represent
                if the Ingress endpoint must be certificate validated.
              type: boolean
          type: object
        status:
          description: CostManagementStatus defines the observed state of CostManagement
          properties:
            api_url:
              description: APIURL is a field of CostManagement to represent the url
                of the API endpoint for service interaction.
              type: string
            authentication:
              description: Authentication is a field of CostManagement to represent
                the authentication status.
              properties:
                credentials_found:
                  description: AuthenticationCredentialsFound is a field of CostManagement
                    to represent if used for uploads were found.
                  type: boolean
                secret_name:
                  description: AuthenticationSecretName is a field of CostManagement
                    to represent the secret with the user and password used for uploads.
                  type: string
                type:
                  description: AuthType is a field of CostManagement to represent
                    the authentication type to be used basic or token.
                  enum:
                  - token
                  - basic
                  type: string
              type: object
            clusterID:
              description: ClusterID is a field of CostManagement to represent the
                cluster UUID.
              type: string
            file_directory:
              description: FileDirectory is a field of CostManagement to represent
                the location of stored files.
              type: string
            file_directory_configured:
              description: FileDirectoryConfigured is a field of CostManagement to
                represent if the location of stored files has been configured.
              type: boolean
            operator_commit:
              description: OperatorCommit is a field of CostManagement that shows
                the commit hash of the operator
              type: string
            prometheus:
              description: Prometheus represents the status of premetheus queries
              properties:
                configuration_error:
                  description: ConfigError is a field of CostManagementStatus to represent
                    errors during prometheus configuration.
                  type: string
                last_query_start_time:
                  description: LastQueryStartTime is a field of CostManagementStatus
                    to represent the last time queries were started.
                  format: date-time
                  nullable: true
                  type: string
                last_query_success_time:
                  description: LastQuerySuccessTime is a field of CostManagementStatus
                    to represent the last time queries were successful.
                  format: date-time
                  nullable: true
                  type: string
                prometheus_configured:
                  description: PrometheusConfigured is a field of CostManagementStatus
                    to represent if cost-management is configured to connect to prometheus.
                  type: boolean
                prometheus_connected:
                  description: PrometheusConnected is a field of CostManagementStatus
                    to represent if prometheus can be queried.
                  type: boolean
                prometheus_connection_error:
                  description: ConnectionError is a field of CostManagementStatus
                    to represent errors during prometheus test query.
                  type: string
                service_address:
                  description: SvcAddress is the internal thanos-querier address.
                  type: string
                skip_tls_verification:
                  description: SkipTLSVerification is a field of CostManagementStatus
                    to represent if the thanos-querier endpoint must be certificate
                    validated
                  type: boolean
              required:
              - prometheus_configured
              - prometheus_connected
              type: object
            reports:
              description: Reports represents the status of report generation
              properties:
                data_collected:
                  description: DataCollected is a field of CostManagementStatus to
                    represent whether or not data was collected for the last query.
                  type: boolean
                data_collection_message:
                  description: DataCollectionMessage is a field of CostManagementStatus
                    to represent a message associated with the data_collected status.
                  type: string
                last_hour_queried:
                  description: LastHourQueried is a field of CostManagementStatus
                    to represent the time range for which metrics were last queried.
                  type: string
                report_month:
                  description: ReportMonth is a field of CostManagementStatus to represent
                    the month for which reports are being generated.
                  type: string
              required:
              - data_collected
              - data_collection_message
              - last_hour_queried
              - report_month
              type: object
            source:
              description: Source is a field of CostManagement to represent the observed
                state of the source on cloud.redhat.com.
              properties:
                check_cycle:
                  description: CheckCycle is a field of CostManagement to represent
                    the number of minutes between each source check schedule The default
                    is 1440 min (24 hours)
                  format: int64
                  type: integer
                error:
                  description: SourceError is a field of CostManagementStatus to represent
                    the error encountered creating the source.
                  type: string
                last_check_time:
                  description: LastSourceCheckTime is a field of CostManagement that
                    shows the time that the last check was attempted
                  format: date-time
                  nullable: true
                  type: string
                name:
                  description: SourceName is a field of CostManagementStatus to represent
                    the source name on cloud.redhat.com.
                  type: string
                source_defined:
                  description: SourceDefined is a field of CostManagementStatus to
                    represent if the source exists as defined on cloud.redhat.com.
                  type: boolean
                sources_path:
                  description: SourcesAPIPath is a field of CostManagement to represent
                    the path of the Sources API service.
                  type: string
              type: object
            upload:
              description: Upload is a field of CostManagement to represent the upload
                object.
              properties:
                ingress_path:
                  description: IngressAPIPath is a field of CostManagement to represent
                    the path of the Ingress API service.
                  type: string
                last_successful_upload_time:
                  description: LastSuccessfulUploadTime is a field of CostManagement
                    that shows the time of the last successful upload
                  format: date-time
                  nullable: true
                  type: string
                last_upload_status:
                  description: LastUploadStatus is a field of CostManagement that
                    shows the http status of the last upload
                  type: string
                last_upload_time:
                  description: LastUploadTime is a field of CostManagement that shows
                    the time that the last upload was attempted
                  format: date-time
                  nullable: true
                  type: string
                upload:
                  description: UploadToggle is a field of CostManagement to represent
                    if the operator should upload to cloud.redhat.com. The default
                    is true
                  type: boolean
                upload_cycle:
                  description: UploadCycle is a field of CostManagement to represent
                    the number of minutes between each upload schedule The default
                    is 360 min (6 hours)
                  format: int64
                  type: integer
                upload_wait:
                  description: UploadWait is a field of CostManagement to represent
                    the time to wait before sending an upload.
                  format: int64
                  type: integer
              type: object
            validate_cert:
              description: ValidateCert is a field of CostManagement to represent
                if the Ingress endpoint must be certificate validated.
              type: boolean
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
